### PR TITLE
Fix Schedule disappear

### LINKED ISSUE #244: Dashboard disappears on CLI Help Command

### PR DESCRIPTION
**Pull request by chrystalquek**
Close #244

### CODE REVIEW

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -289,6 +289,11 @@ private void updateDetailsPanel() {
         rightPanelPlaceholder.getChildren().clear();
 
         switch (mode) {
+        case DASHBOARD:
+            if (!rightPanelPlaceholder.getChildren().contains(calendarListPanel.getRoot())) {
+                rightPanelPlaceholder.getChildren().add(calendarListPanel.getRoot());
```
Comment (shadowezz) [inline src/main/java/seedu/address/ui/MainWindow.java:294]: Dont need a condition right since the rightPanelPlaceholder is cleared.

**Review by shadowezz — APPROVED** [review]
LGTM
